### ISSUE TITLE
0.16.0 fails to build in windows (but 0.15.0 does not)

### ISSUE THREAD

**Issue by Ivanca** [polotek/libxmljs#371]
The error I was getting was:
```
xml_node.obj : error LNK2001: unresolved external symbol "struct _xmlNode * __cdecl libxmljs::get_wrapped_node_in_children(struct _xmlNode *,void *)" (?get_wrapped_node_in_ch ildren@libxmljs@@YAPEAU_xmlNode@@PEAU2@PEAX@Z) [C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmljs\build\xmljs.vcxproj]
C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmljs\build\Release\xmljs.node : fatal error LNK1120: 1 unresolved externals [C:\Users\Ivan\Dropbox\labs\cs\node_modules\libxmlj s\build\xmljs.vcxproj]
```
Using the 0.15.0 version -instead of the new one- fixed the issue (`npm install libxmljs@0.15.0`)

**Comment by teleological** [comment]
I just merged PR #368 from @jhs67, which I think will fix this. Please let me know.

**Comment by teleological** [comment]
Released in 0.16.1

**Comment by thomasmilleratosnet** [comment]
0.16.1 still doesn't install on WIndows. (node-gyp rebuild fails).
Here is the npm debug log:
629 info install libxmljs@0.16.1
630 verbose unsafe-perm in lifecycle true
631 info libxmljs@0.16.1 Failed to exec install script
632 verbose unlock done using C:\Users\de402438\AppData\Roaming\npm-cache\_locks\libxmljs-25b2e933e43e6c4f.lock for C:\Users\de402438\node_modules\libxmljs
633 verbose stack Error: libxmljs@0.16.1 install: `node-gyp rebuild`
633 verbose stack Exit status 1
633 verbose stack     at EventEmitter.<anonymous> (C:\MeineProgramme\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
633 verbose stack     at emitTwo (events.js:87:13)
633 verbose stack     at EventEmitter.emit (events.js:172:7)
633 verbose stack     at ChildProcess.<anonymous> (C:\MeineProgramme\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
633 verbose stack     at emitTwo (events.js:87:13)
633 verbose stack     at ChildProcess.emit (events.js:172:7)
633 verbose stack     at maybeClose (internal/child_process.js:821:16)
633 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
634 verbose pkgid libxmljs@0.16.1
635 verbose cwd C:\Users\de402438
636 error Windows_NT 6.1.7601
637 error argv "C:\\MeineProgramme\\nodejs\\node.exe" "C:\\MeineProgramme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "libxmljs@0.16.1"
638 error node v4.3.1
639 error npm  v2.14.12
640 error code ELIFECYCLE
641 error libxmljs@0.16.1 install: `node-gyp rebuild`
641 error Exit status 1
642 error Failed at the libxmljs@0.16.1 install script 'node-gyp rebuild'.
642 error This is most likely a problem with the libxmljs package,
642 error not with npm itself.
642 error Tell the author that this fails on your system:
642 error     node-gyp rebuild
642 error You can get their info via:
642 error     npm owner ls libxmljs
642 error There is likely additional logging output above.
643 verbose exit [ 1, true ]
