### ISSUE TITLE
Does not build on iojs 2.0.0

### ISSUE THREAD

**Issue by marcominetti** [polotek/libxmljs#310]
```
 ...
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/libxmljs.h:7,
                 from ../src/libxmljs.cc:7:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from ../src/libxmljs.cc:3:0:
/home/marco.minetti/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/marco.minetti/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory `/home/marco.minetti/Desktop/test/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by arthurschreiber** [comment]
I think a bump of `nan` to the latest version should fix this.

**Comment by marcominetti** [comment]
Yep, I've already created a pr, in a couple of ours I'll change it to be merged

**Comment by marcominetti** [comment]
#311

**Comment by defunctzombie** [comment]
v0.14.1 should work
